import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = { title: 'Terms of Service - HypeCTR' }

export default function TermsPage() {
  return (
    <div style={{ background: 'var(--bg)', minHeight: '100vh', color: 'var(--text)', padding: '80px 24px' }}>
      <div style={{ maxWidth: 720, margin: '0 auto' }}>
        <Link href="/" style={{ color: 'var(--accent)', fontSize: 14, textDecoration: 'none', display: 'inline-block', marginBottom: 40 }}>
          ← Back to HypeCTR
        </Link>
        <h1 style={{ fontSize: 36, fontWeight: 800, letterSpacing: '-1px', marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ color: 'var(--muted)', fontSize: 14, marginBottom: 48 }}>Last updated: May 2026</p>

        <Section title="Acceptance of Terms">
          By using HypeCTR, you agree to these Terms of Service. If you do not agree, please do not use the service.
        </Section>

        <Section title="Use of Service">
          HypeCTR is a tool for analysing publicly available YouTube channel data and generating video ideas. You may only submit YouTube channel URLs for channels you are authorised to analyse. You must not use HypeCTR to harvest data at scale, circumvent YouTube&apos;s terms of service, or for any unlawful purpose.
        </Section>

        <Section title="Free Tier">
          The free tier allows 3 channel analyses per day and returns 1 ranked idea per analysis. Free-tier limits are enforced via a browser cookie. Attempting to circumvent these limits is prohibited.
        </Section>

        <Section title="Pro Subscription">
          Pro subscriptions are available on a monthly ($19/month) or annual ($180/year) billing cycle via Stripe. Pro includes up to 25 AI thumbnail generations per calendar month; unused generations do not roll over. You may cancel at any time. Cancellation takes effect at the end of your current billing period. We do not offer refunds for partial billing periods.
        </Section>

        <Section title="AI-Generated Content">
          Video ideas and thumbnail concepts are generated by AI and are provided for informational purposes only. HypeCTR makes no guarantees about the accuracy, originality, or performance of AI-generated content. You are solely responsible for any content you publish.
        </Section>

        <Section title="Intellectual Property">
          HypeCTR and its underlying technology are owned by HypeCTR. AI-generated ideas and thumbnails produced using our service may be used by you freely. We claim no ownership over outputs generated on your behalf.
        </Section>

        <Section title="Limitation of Liability">
          HypeCTR is provided &ldquo;as is&rdquo; without warranties of any kind. To the maximum extent permitted by law, HypeCTR is not liable for any indirect, incidental, or consequential damages arising from your use of the service.
        </Section>

        <Section title="Contact">
          For questions about these terms, visit our <Link href="/contact" style={{ color: 'var(--accent)' }}>contact page</Link>.
        </Section>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 40 }}>
      <h2 style={{ fontSize: 20, fontWeight: 700, marginBottom: 12, letterSpacing: '-0.3px' }}>{title}</h2>
      <p style={{ fontSize: 15, color: 'var(--muted)', lineHeight: 1.8 }}>{children}</p>
    </div>
  )
}
